#support multiple orgs eventually
org: Hyrule Ventures
org_desc:  Mining Rupees Daily
users:
  - username: link
    email: link@hyrule.com
    first_name: Link
    is_superuser: yes
    last_name: Smith
  - username: gdorf
    email: gannon@hyrule.com
    first_name: Gannon
    is_superuser: false
    last_name: Dorf
  - username: zelda
    email: zelda@hyrule.com
    first_name: Zelda
    is_superuser: false
    last_name: Smith
  - username: epona
    email: epona@hyrule.com
    first_name: Epona
    is_superuser: false
    last_name: Horse
  - username: demise
    email: demise@hyrule.com
    first_name: De
    is_superuser: false
    last_name: Mise

teams:
  - name: Ops
    description: The Ops Team
    users:
    - link
  - name: QA
    description: The QA Team
    users:
    - gdorf
  - name: Dev
    description: The Dev Team
    users:
    - zelda

credentials:
  - name: EC2 SSH
    description:  Used for EC2 instances
    team: Ops
    kind: ssh
    username: root
    private_key: /Users/jmartin/.ssh/ida_rsa
  - name: Local SSH
    description:  Used for vagrant instances
    team: Ops
    kind: ssh
    username: vagrant
    private_key: /Users/jmartin/.vagrant.d/insecure_private_key
  - name: AWS creds
    description: Used for AWS 
    team: Ops
    kind: aws
    username: YOU
    password: CANTHANDLETHIS
  - name: RAX creds
    description: Used for Rackspace 
    team: Ops
    kind: rax
    username: me
    password: noyoucant

inventories:
  - name: Production
    description: Production Machines
    groups:
      - name: EC2
        credential: AWS creds
        source: ec2
        description: EC2 hosts
      - name: RAX
        credential: RAX creds
        source: rax
        description: RAX hosts
  - name: Test
    description: Test Machines
    groups:
      - name: web
        source: manual
        hosts:
        - name: 10.42.0.6
        - name: 10.42.0.7
        - name: 10.42.0.8
        - name: 10.42.0.9
        - name: 10.42.0.10     
  - name: QA
    description: QA Machines

projects:
  - name: Hyrulian Playbooks
    description: Configures all the servers in Hyrule.
    scm_type: git
    scm_url: https://github.com/jsmartin/tower-demo-example-simple
  - name: Ansible Examples
    description: Some example roles and playbooks
    scm_type: git
    scm_url: https://github.com/ansible/ansible-examples

job_templates:
  - name: Apache
    description: Confgure Apache servers
    inventory: Test
    project: Hyrulian Playbooks
    playbook: site.yml
    machine_credential: Local SSH
    job_type: run
    verbosity: 0
    forks: 5
